version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: dockerization/Dockerfile
    ports:
      - "8080:${PROJECT_PORT}"
    volumes:
      - "./src:/app"
      - "./.env:/app/.env"
    env_file:
      - .env
    command: python3 main.py
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  db-data:
